#index:
#    path: /
#    controller: App\Controller\DefaultController::index

blog_posts:
    path: /{_locale}/posts
    controller: App\Controller\PostsController::posts
    requirements: {_locale: '%router.locales%', display_order: 'created_at'}


new_blog_post:
    path: /{_locale}/posts/new
    controller: App\Controller\PostsController::addPost
    requirements: {_locale: '%router.locales%'}

blog_search:
    path: /{_locale}/posts/search
    controller: App\Controller\PostsController::search
    requirements: {_locale: '%router.locales%'}

blog_post_edit:
    path: /{_locale}/posts/{slug}/edit
    controller: App\Controller\PostsController::edit
    requirements: {_locale: '%router.locales%'}

blog_post_delete:
    path: /{_locale}/posts/{slug}/delete
    controller: App\Controller\PostsController::delete
    requirements: {_locale: '%router.locales%'}

blog_show:
    path: /{_locale}/posts/{slug}
    controller: App\Controller\PostsController::post
    requirements: {_locale: '%router.locales%'}

register:
    path: /{_locale}/register
    controller: App\Controller\RegisterController::register
    requirements: {_locale: '%router.locales%'}

email_confirmation:
    path: /{_locale}/confirm/{code}
    controller: App\Controller\RegisterController::confirmEmail
    requirements: {_locale: '%router.locales%'}

app_reset_password:
    path: /{_locale}/reset/{token?}
    controller: App\Controller\ResetPasswordController::reset
    requirements: {_locale: '%router.locales%'}

app_forgot_password_request:
    path: /{_locale}/reset-password
    controller: App\Controller\ResetPasswordController::request
    requirements: {_locale: '%router.locales%'}

app_check_email:
    path: /{_locale}/reset-password/check-email
    controller: App\Controller\ResetPasswordController::checkEmail
    requirements: {_locale: '%router.locales%'}

login:
    path: /{_locale}/login
    controller: App\Controller\SecurityController::login
    requirements: {_locale: '%router.locales%'}

logout:
    path: /{_locale}/logout
    controller: App\Controller\SecurityController::logout
    requirements: {_locale: '%router.locales%'}