#index:
#    path: /
#    controller: App\Controller\DefaultController::index

blog_posts:
    path: /{_locale}/posts
    controller: App\Controller\PostsController::posts
    requirements: {_locale: '%router.locales%'}


new_blog_post:
    path: /{_locale}/posts/new
    controller: App\Controller\PostsController::addPost
    requirements: {_locale: '%router.locales%'}

blog_search:
    path: /{_locale}/posts/search
    controller: App\Controller\PostsController::search
    requirements: {_locale: '%router.locales%'}

blog_post_edit:
    path: /{_locale}/posts/{slug}/edit
    controller: App\Controller\PostsController::edit
    requirements: {_locale: '%router.locales%'}

blog_post_delete:
    path: /{_locale}/posts/{slug}/delete
    controller: App\Controller\PostsController::delete
    requirements: {_locale: '%router.locales%'}

blog_show:
    path: /{_locale}/posts/{slug}
    controller: App\Controller\PostsController::post
    requirements: {_locale: '%router.locales%'}
